name: Create a new issue report
description: Create a new issue report for Export-RecipientPermissions.
title: "<a short and pregnant title for your issue>"
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to fill out this issue report!**

        Support in this GitHub repository is free, voluntary and without guaranteed response times.

        If you want to prioritize your request, please use [ExplicIT Consulting's **fee-based support**](https://explicitconsulting.at/open-source/export-recipientpermissions/) instead of this form.
  - type: checkboxes
    id: usinglatestrelease
    attributes:
      label: Issue happens in the latest release
      description: By submitting this issue, you confirm that the issue happens in the [latest release](https://github.com/GruberMarkus/Export-RecipientPermissions/releases/latest) of Export-RecipientPermissions.
      options:
        - label: I confirm that the issue happens in the latest release of Export-RecipientPermissions
          required: true
  - type: checkboxes
    id: previousissuesanddocumentation
    attributes:
      label: Previously solved issues and documentation
      description: Before creating a new issue, check the documentation ([README](https://github.com/GruberMarkus/Export-RecipientPermissions) and associated documents), previous [issues](https://github.com/GruberMarkus/Export-RecipientPermissions/issues?q=) and [discussions](https://github.com/GruberMarkus/Export-RecipientPermissions/discussions?discussions_q=).
      options:
        - label: I have searched through issues, discussions and documentation, but have not found an answer to my issue
          required: true
  - type: checkboxes
    id: codeofconduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/GruberMarkus/Export-RecipientPermissions?tab=coc-ov-file).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Tell us what you expected to happen, what really happened and how the problem can be reproduced.
        Additionally, upload screenshots and other files that may help analyze the problem.
      placeholder:
    validations:
      required: true
