blank_issues_enabled: false
contact_links:
  - name: Commercial support from ExplicIT Consulting
    url: https://explicitconsulting.at/open-source/Export-RecipientPermissions
    about: If you want to prioritize your request, please use ExplicIT Consulting's commercial support instead of this form.
  - name: Documentation
    url: https://github.com/GruberMarkus/Export-RecipientPermissions
    about: Before creating a new issue, check the documentation (README file and associated documents).
  - name: Issues
    url: https://github.com/GruberMarkus/Export-RecipientPermissions/issues?q=
    about: Before creating a new issue, search previous issues.
  - name: Discussions board
    url: https://github.com/GruberMarkus/Export-RecipientPermissions/discussions?discussions_q=
    about: Before creating a new issue, search discussions. You are welcome to share your experiences with Export-RecipientPermissions, exchange ideas with other users or suggest new features in our discussions board.
